name: WhatTheForecast Build & Test

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  # --- Задание для Unit-тестов (быстрое) ---
  unit-test:
    runs-on: macos-14
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Select Xcode version
        run: sudo xcode-select -s /Applications/Xcode_16.1.app/Contents/Developer

      # --- ШАГ 1: Кэширование ---
      # Кэшируем DerivedData и SPM, чтобы ускорить сборку.
      # Ключ кэша зависит от хэша файла Package.resolved, чтобы кэш сбрасывался при изменении зависимостей.
      - name: Cache Xcode build products
        uses: actions/cache@v4
        with:
          path: |
            ~/Library/Developer/Xcode/DerivedData
            .build
          key: ${{ runner.os }}-xcode-${{ hashFiles('WhatTheForecast.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-xcode-

      - name: Install xcpretty
        run: gem install xcpretty

      # --- ШАГ 2: Динамический поиск симулятора ---
      - name: Find iPhone 16 Pro Simulator UDID
        id: simulator
        run: |
          UDID=$(xcrun simctl list devices 'iPhone 16 Pro' --json | jq -r '.devices | .[] | .[] | select(.isAvailable == true and .state == "Shutdown") | .udid' | head -n 1)
          echo "SIMULATOR_UDID=$UDID" >> "$GITHUB_ENV"
          echo "Found simulator UDID: $UDID"
      
      # --- ШАГ 3: Запуск только Unit-тестов ---
      - name: Build and Run Unit Tests
        run: |
          set -o pipefail && xcodebuild \
            test \
            -workspace WhatTheForecast.xcodeproj/project.xcworkspace \
            -scheme WhatTheForecast \
            -destination "id=${{ env.SIMULATOR_UDID }}" \
            -only-testing:WhatTheForecastTests \
            -skipPackagePluginValidation | xcpretty

  # --- Задание для UI-тестов (медленное, выполняется параллельно) ---
  ui-test:
    runs-on: macos-14
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Select Xcode version
        run: sudo xcode-select -s /Applications/Xcode_16.1.app/Contents/Developer

      - name: Cache Xcode build products
        uses: actions/cache@v4
        with:
          path: |
            ~/Library/Developer/Xcode/DerivedData
            .build
          key: ${{ runner.os }}-xcode-${{ hashFiles('WhatTheForecast.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-xcode-

      - name: Install xcpretty
        run: gem install xcpretty
      
      - name: Find iPhone 16 Pro Simulator UDID
        id: simulator
        run: |
          UDID=$(xcrun simctl list devices 'iPhone 16 Pro' --json | jq -r '.devices | .[] | .[] | select(.isAvailable == true and .state == "Shutdown") | .udid' | head -n 1)
          echo "SIMULATOR_UDID=$UDID" >> "$GITHUB_ENV"
          echo "Found simulator UDID: $UDID"

      # --- Запуск только UI-тестов ---
      - name: Build and Run UI Tests
        run: |
          set -o pipefail && xcodebuild \
            test \
            -workspace WhatTheForecast.xcodeproj/project.xcworkspace \
            -scheme WhatTheForecast \
            -destination "id=${{ env.SIMULATOR_UDID }}" \
            -only-testing:WhatTheForecastUITests \
            -skipPackagePluginValidation | xcpretty