name: WhatTheForecast Build & Test

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: macos-14

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Select Xcode version
        run: sudo xcode-select -s /Applications/Xcode_16.1.app/Contents/Developer

      - name: List available simulators  
        run: |
          echo "=== Available Simulators ==="
          xcrun simctl list devices available
          echo ""
          echo "=== Available Device Types ==="
          xcrun simctl list devicetypes
          echo ""
          echo "=== Available Runtimes ==="
          xcrun simctl list runtimes

      - name: Install xcpretty
        run: gem install xcpretty

      - name: Build and run tests
        run: |
          set -o pipefail && xcodebuild \
            -workspace WhatTheForecast.xcodeproj/project.xcworkspace \
            -scheme WhatTheForecast \
            -sdk iphonesimulator \
            -destination 'id=86E5E9E0-DB93-4EA2-8A61-F5EEA12BE23D' \
            -skipPackagePluginValidation
            test | xcpretty