name: WhatTheForecast Build & Test

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: macos-14

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Select Xcode version
        run: sudo xcode-select -s /Applications/Xcode_16.1.app/Contents/Developer

      - name: List available simulators  
        run: |
          echo "=== Available Simulators ==="
          xcrun simctl list devices available
          echo ""
          echo "=== Available Device Types ==="
          xcrun simctl list devicetypes
          echo ""
          echo "=== Available Runtimes ==="
          xcrun simctl list runtimes

    #   - name: Install and Run SwiftLint
    #     run: |
    #       brew install swiftlint
    #       swiftlint --strict --reporter "github-actions-logging"

      - name: Install xcpretty
        run: gem install xcpretty

      - name: Build and run tests
        run: |
          set -o pipefail && xcodebuild \
            -workspace WhatTheForecast.xcodeproj/project.xcworkspace \
            -scheme WhatTheForecast \
            -sdk iphonesimulator \
            -destination 'platform=iOS Simulator,name=iPhone 16 Pro,OS=18.2' \
            test | xcpretty