name: WhatTheForecast Build & Test

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: macos-14

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Select Xcode version
        run: sudo xcode-select -s /Applications/Xcode_16.1.app/Contents/Developer

      - name: List available simulators  
        run: |
          echo "=== Available Simulators ==="
          xcrun simctl list devices available
          echo ""
          echo "=== Available Device Types ==="
          xcrun simctl list devicetypes
          echo ""
          echo "=== Available Runtimes ==="
          xcrun simctl list runtimes

      - name: Install xcpretty
        run: gem install xcpretty

      - name: Build for testing
        run: |
          set -o pipefail && xcodebuild \
            build-for-testing \
            -workspace WhatTheForecast.xcodeproj/project.xcworkspace \
            -scheme WhatTheForecast \
            -destination 'id=86E5E9E0-DB93-4EA2-8A61-F5EEA12BE23D' \
            -skipPackagePluginValidation | xcpretty

      - name: Run tests
        run: |
          XCTESTRUN_FILE=$(find ~/Library/Developer/Xcode/DerivedData -name '*.xctestrun' | head -n 1)
          echo "Found xctestrun file: $XCTESTRUN_FILE"
              
          set -o pipefail && xcodebuild \
          test-without-building \
          -xctestrun "$XCTESTRUN_FILE" \
          -destination 'id=86E5E9E0-DB93-4EA2-8A61-F5EEA12BE23D' | xcpretty